[workspace]
members = ["programs/*"]

[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zec_dark_perps = "7TeV1Vdps9eaMv8mfcXJgNsEzWBJwNi4kHfqaVkEu95u"

[programs.devnet]
zec_dark_perps = "7TeV1Vdps9eaMv8mfcXJgNsEzWBJwNi4kHfqaVkEu95u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[arcium]
version = "0.4.0"

[localnet]
# Number of MPC nodes in the cluster
nodes = 2
# Timeout for localnet to start (seconds)
localnet_timeout_secs = 120
# MPC backends (Cerberus is the default)
backends = ["Cerberus"]

[test.validator]
bind_address = "127.0.0.1"
